### Create request to add a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe with Billing account",
  "email": "test@sgg.com",
  "address": "E 10/19 Paikpara Street",
  "dateOfBirth": "1996-09-27",
  "registeredDate": "2025-08-13"
}
